import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width > 480;

export const styles = StyleSheet.create({
  homeContainer: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    // Limita a largura no iPad/Web, mas deixa flexível no celular
    alignSelf: isTablet ? 'center' : 'stretch',
    width: isTablet ? 480 : '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: isTablet ? 0.15 : 0,
    shadowRadius: 50,
    elevation: isTablet ? 10 : 0,
  },
  homeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 40, // Espaço para StatusBar
    paddingBottom: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.03)',
    zIndex: 100,
  },
  headerBrandContainer: {
    justifyContent: 'center',
  },
  cartBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    padding: 10,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#1A1A1A',
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  badgeText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  categoryScroll: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 12,
  },
  categoryItem: {
    paddingHorizontal: 22,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EAEAEA',
    borderRadius: 100,
    marginRight: 12,
    justifyContent: 'center',
  },
  categoryItemActive: {
    backgroundColor: '#FF8C00',
    borderColor: '#FF8C00',
  },
  categoryText: {
    fontWeight: '600',
    color: '#666',
    fontSize: 14,
  },
  categoryTextActive: {
    color: '#FFF',
  },
  productList: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 170, // Espaço para os botões FABs
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 50,
  },
  centerText: {
    marginTop: 10,
    fontWeight: '600',
    color: '#A0A0A0',
  },
  productCard: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 14,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    marginBottom: 16,
  },
  cardExpanded: {
    borderColor: 'rgba(255, 140, 0, 0.3)',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    transform: [{ translateY: -2 }],
  },
  prodImg: {
    width: 100,
    height: 100,
    borderRadius: 18,
    backgroundColor: '#F5F5F5',
  },
  prodInfo: {
    flex: 1,
    marginLeft: 16,
    justifyContent: 'space-between',
  },
  prodTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  prodDesc: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
    marginBottom: 10,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 'auto',
  },
  prodPrice: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1A1A',
  },
  addBtn: {
    backgroundColor: '#1A1A1A',
    width: 36,
    height: 36,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  adminFab: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    backgroundColor: '#1A1A1A',
    width: 54,
    height: 54,
    borderRadius: 27,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    zIndex: 1000,
  },
  helpFab: {
    position: 'absolute',
    bottom: 95,
    right: 20,
    backgroundColor: '#FF8C00',
    width: 54,
    height: 54,
    borderRadius: 27,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#FF8C00',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    zIndex: 1000,
  },
  toastAlert: {
    position: 'absolute',
    bottom: 100,
    alignSelf: 'center',
    backgroundColor: '#1A1A1A',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 30,
    zIndex: 2000,
  },
  toastText: {
    color: '#FFFFFF',
    marginLeft: 10,
    fontWeight: '600',
    fontSize: 14,
  }
});